baseURL = 'https://picklejuicedev.github.io/'
languageCode = 'en-us'
title = 'picklejuice'
theme = 'spectral'
icon = 'images/icon_dark.png'

[params]
fancyTitle = "picklejuice" # title for frontpage, may include image
copyright = "picklejuice"
description = """For the <a href="/posts/">fine bits</a> between the pickles<br/> 
                Adding nutricious solutions <br/> to tech teams and  R&D projects<br/>
                """
startbuttonText = "contact"
startbuttonLink = "#contact"
body_is_markdown = true

[[params.menu.main]]
url = '/'
title = "Home"

#[[params.menu.main]]
#url = '/posts/'
#title = "Posts"

[[params.menu.main]]
url = '/aboutme/'
title = "About"

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[[params.cta.link]]
href = "#"
text = "Learn More"
special = false


[params.one]
enable = true
title = 'In a pickle?'
body = '''
My name is Sean Westgate, and I am an entrepreneurial 
technologist with over 20 years experience driving innovation, 
building products, running teams and growing businesses. 
I took my first company, Green Hippo Ltd, all the way from 
startup through to a new home within a parent group and am 
now working as a Technical Consultant helping tech teams 
improve to deliver disruptive products.

If you are looking to upgrade your tooling or processes, review 
your tech strategy or simply have a challenging technical problem, drop me a line.

Just add some Picklejuice ;)'''


[params.two]
enable = false

[[params.two.section]]
img = "images/datashader.png"
link = "/posts/datashader/"
title = 'Visualise millions of datapoints'
body = """There are a ton of awesome data visualisation packages out 
there, but most require you to wrangle the data into a particular 
way to be able to look at it.  """

[[params.two.section]]
img = "images/kedro.png"
link = "/posts/kedro/"
title = 'Kedro'
body = """Creating well structured and reproducable data science 
projects with this awesome library."""

[[params.two.section]]
img = "images/coding.jpg"
link = "/posts/markdown-syntax/"
title = 'Turbo charge your<br />Dev team'
body = """The difference between doing ok and really 
getting things done rarely depends on devs. 
Really understanding what you are building and commincating it effectivly is key. Go faster by not building what you don't need."""


[params.contact]
enable = true
title = "Contact"
body = "Leave me a message."
address = "1234 Somewhere Road<br />Some Place, Some State 0000<br />Some Country"
email = "sean@pickle-juice.co.uk"
subject = "New Submission!"
plain = false