baseURL = 'https://picklejuicedev.github.io/'
languageCode = 'en-us'
title = 'picklejuice'
theme = 'spectral'
icon = 'images/icon_dark.png'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[params]
fancyTitle = "picklejuice" # title for frontpage, may include image
copyright = "picklejuice"
description = """For the <a href="/posts/">fine bits</a> between the pickles<br/> 
                Adding nutricious solutions <br/> to tech teams and  R&D projects<br/>
                """
startbuttonText = "contact"
startbuttonLink = "#contact"
body_is_markdown = true

[[params.menu.main]]
url = '/'
title = "Home"

[[params.menu.main]]
url = '/posts/'
title = "Posts"

[[params.menu.main]]
url = '/aboutme/'
title = "About"

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[[params.cta.link]]
href = "#"
text = "Learn More"
special = false


[params.one]
enable = true
title = 'In a pickle?'
body = '''
I am [Sean Westgate](/aboutme), an entrepreneurial technologist with over 20 
years' experience driving innovation, building products, running 
teams and growing businesses. As the founder, CEO and CTO I took 
Green Hippo Ltd from a startup through to a successful international 
business. Now that it has found a new home within a parent group, I 
am working as a Technical Consultant helping tech teams improve to 
deliver disruptive products.

If you are looking to upgrade your tooling or processes, review 
your tech strategy or simply have a challenging technical problem, drop me a line.

Just add some Picklejuice ;)'''


[params.two]
enable = true

[[params.two.section]]
img = "images/coding.jpg"
link = "/posts/tools_overview/"
title = 'Tools Infrastructure for Production'
body = """What tools and  processes do you need to think about when building 
production ready code? An what value or benefit are you hoping to 
get from investing in them?  """

[params.contact]
enable = true
title = "Contact"
body = "Leave me a message."
address = "1234 Somewhere Road<br />Some Place, Some State 0000<br />Some Country"
email = "sean@pickle-juice.co.uk"
subject = "New Submission!"
plain = false